apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: tinyllama-1-1b-chat-v1-0-modelcar
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
  name: tinyllama-1-1b-chat-v1-0-modelcar
  namespace: summit-connect-2025
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "2"
          memory: 10Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 10Gi
          nvidia.com/gpu: "1"
      runtime: tinyllama-1-1b-chat-v1-0-modelcar
      storageUri: oci://quay.io/redhat-telco-adoption/tinyllama-1-1b-chat-v1-0-modelcar:latest
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
