apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: tinyllama-1b
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    app.kubernetes.io/name: tinyllama-1b
    app.kubernetes.io/component: model-serving
    app.kubernetes.io/part-of: llamastack-trustyai-demo
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
  name: tinyllama-1b
  namespace: summit-connect-2025
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "2"
          memory: 6Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
      runtime: tinyllama-1b
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:tinyllama-1.1b-chat-v1.0
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists