apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamastack-playground-trustyai
  labels:
    app.kubernetes.io/name: llamastack-playground-trustyai
    app.kubernetes.io/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llamastack-playground-trustyai
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llamastack-playground-trustyai
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: playground
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        image: "quay.io/rh-aiservices-bu/llama-stack-playground:0.2.11"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8501
          protocol: TCP
        env:
        - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
          value: "false"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: LLAMA_STACK_ENDPOINT
          value: "http://llamastack-trustyai-fms-service.summit-connect-2025.svc.cluster.local:8321"
        - name: DEFAULT_MODEL
          value: "tinyllama-1b"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
