apiVersion: v1
data:
  URI: b2NpOi8vcXVheS5pby9yZWRoYXQtYWktc2VydmljZXMvbW9kZWxjYXItY2F0YWxvZzpncmFuaXRlLTQuMC1oLW1pY3Jv
kind: Secret
metadata:
  annotations:
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/description: ""
    openshift.io/display-name: granite-4-0-h-micro
  labels:
    opendatahub.io/dashboard: "true"
  name: granite-4-0-h-micro
  namespace: summit-connect-2025
type: Opaque
