apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: granite-4-0-h-micro
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
  name: granite-4-0-h-micro
  namespace: summit-connect-2025
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 8Gi
          nvidia.com/gpu: "1"
      runtime: granite-4-0-h-micro
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:granite-4.0-h-micro
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
