kind: ConfigMap
apiVersion: v1
metadata:
  name: guardrails-orchestrator-config
  labels:
    app.kubernetes.io/name: guardrails-orchestrator-config
    app.kubernetes.io/component: safety-shields
    app.kubernetes.io/part-of: llamastack-trustyai-demo
data:
  config.yaml: |
    detectors:
      regex:
        type: text_contents
        service:
            hostname: "127.0.0.1"
            port: 8080
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      hap:
        type: text_contents
        service: 
          hostname: "granite-guardian-hap-38m-predictor"
          port: 8000
        chunker_id: whole_doc_chunker
        default_threshold: 0.5