apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: "Granite Guardian HAP 38M"
    serving.kserve.io/deploymentMode: RawDeployment
    app.openshift.io/runtime: ml-model
    app.openshift.io/runtime-version: "38m"
  labels:
    app.kubernetes.io/name: granite-guardian-hap-38m
    app.kubernetes.io/component: safety-detector
    app.kubernetes.io/part-of: llamastack-trustyai-demo
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
  name: granite-guardian-hap-38m
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: guardrails-detector-hf-runtime
      name: ""
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
      runtime: granite-guardian-hap-38m
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:granite-guardian-hap-38m