apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
    notebooks.opendatahub.io/last-image-selection: minimal-gpu:2025.2
    notebooks.opendatahub.io/last-image-version-git-commit-selection: d3137ca
    notebooks.opendatahub.io/last-size-selection: Small
    notebooks.opendatahub.io/oauth-logout-url: https://rhods-dashboard-redhat-ods-applications.apps.cluster-5j7rq.5j7rq.sandbox1562.opentlc.com/projects/summit-connect-2025?notebookLogout=llamastack-safety-demo
    opendatahub.io/accelerator-name: ""
    opendatahub.io/accelerator-profile-namespace: ""
    opendatahub.io/hardware-profile-name: ""
    opendatahub.io/hardware-profile-namespace: ""
    opendatahub.io/image-display-name: Jupyter | Minimal | CUDA | Python 3.12
    opendatahub.io/legacy-hardware-profile-name: ""
    opendatahub.io/username: admin
    opendatahub.io/workbench-image-namespace: ""
    openshift.io/description: ""
    openshift.io/display-name: llamastack-safety-demo
  labels:
    app: llamastack-safety-demo
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
    opendatahub.io/user: admin
  name: llamastack-safety-demo
  namespace: summit-connect-2025
spec:
  template:
    spec:
      initContainers:
      - name: setup-workspace
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/minimal-gpu:2025.2
        env:
        - name: GIT_REPO_URL
          value: "https://github.com/jlmayorga/llamastack.git"
        - name: GIT_SSL_CAINFO
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        command:
        - /bin/sh
        - -c
        - |
          echo "Init container started at $(date)"

          if [ -n "$GIT_REPO_URL" ]; then
            echo "Cloning repository from: $GIT_REPO_URL"

            # Extract repo name from URL
            REPO_NAME=$(basename "$GIT_REPO_URL" .git)
            TARGET_DIR="/opt/app-root/src/$REPO_NAME"

            # Clone only the notebooks subdirectory using sparse-checkout
            mkdir -p "$TARGET_DIR"
            cd "$TARGET_DIR"

            git init
            git remote add origin "$GIT_REPO_URL"
            git config core.sparseCheckout true
            echo "notebooks/*" >> .git/info/sparse-checkout

            if git pull origin main; then
              echo "Successfully cloned notebooks subdirectory to $TARGET_DIR"
              ls -la "$TARGET_DIR"
            else
              echo "Failed to clone repository"
              exit 1
            fi
          else
            echo "No GIT_REPO_URL provided, skipping git clone"
          fi

          echo "Workspace setup complete!"
        volumeMounts:
        - mountPath: /opt/app-root/src/
          name: llamastack-safety-demo-storage
        - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
                              --ServerApp.token=''
                              --ServerApp.password=''
                              --ServerApp.base_url=/notebook/summit-connect-2025/llamastack-safety-demo
                              --ServerApp.quit_button=False
                              --ServerApp.tornado_settings={"user":"admin","hub_host":"https://rhods-dashboard-redhat-ods-applications.apps.cluster-5j7rq.5j7rq.sandbox1562.opentlc.com","hub_prefix":"/projects/summit-connect-2025"}
        - name: JUPYTER_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/minimal-gpu:2025.2
        - name: PIP_CERT
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: SSL_CERT_FILE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: GIT_SSL_CAINFO
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/minimal-gpu:2025.2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/summit-connect-2025/llamastack-safety-demo/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: llamastack-safety-demo
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/summit-connect-2025/llamastack-safety-demo/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 8Gi
        volumeMounts:
        - mountPath: /opt/app-root/src/
          name: llamastack-safety-demo-storage
        - mountPath: /dev/shm
          name: shm
        - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
        - mountPath: /opt/app-root/pipeline-runtimes/
          name: runtime-images
        workingDir: /opt/app-root/src
      - args:
        - --provider=openshift
        - --https-address=:8443
        - --http-address=
        - --openshift-service-account=llamastack-safety-demo
        - --cookie-secret-file=/etc/oauth/config/cookie_secret
        - --cookie-expire=24h0m0s
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --upstream=http://localhost:8888
        - --upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --email-domain=*
        - --skip-provider-button
        - --client-id=llamastack-safety-demo-summit-connect-2025-oauth-client
        - --client-secret-file=/etc/oauth/client/secret
        - --scope=user:info user:check-access
        - --openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"llamastack-safety-demo","namespace":"$(NAMESPACE)"}
        - --logout-url=https://rhods-dashboard-redhat-ods-applications.apps.cluster-5j7rq.5j7rq.sandbox1562.opentlc.com/projects/summit-connect-2025?notebookLogout=llamastack-safety-demo
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.redhat.io/openshift4/ose-oauth-proxy-rhel9@sha256:c174c11374a52ddb7ecfa400bbd9fe0c0f46129bd27458991bec69237229ac7d
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: oauth-proxy
        ports:
        - containerPort: 8443
          name: oauth-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/oauth/client
          name: oauth-client
        - mountPath: /etc/oauth/config
          name: oauth-config
        - mountPath: /etc/tls/private
          name: tls-certificates
      enableServiceLinks: false
      serviceAccountName: llamastack-safety-demo
      volumes:
      - name: llamastack-safety-demo-storage
        persistentVolumeClaim:
          claimName: llamastack-safety-demo-storage
      - emptyDir:
          medium: Memory
        name: shm
      - configMap:
          items:
          - key: ca-bundle.crt
            path: ca-bundle.crt
          name: workbench-trusted-ca-bundle
          optional: true
        name: trusted-ca
      - name: oauth-config
        secret:
          defaultMode: 420
          secretName: llamastack-safety-demo-oauth-config
      - name: oauth-client
        secret:
          defaultMode: 420
          secretName: llamastack-safety-demo-oauth-client
      - name: tls-certificates
        secret:
          defaultMode: 420
          secretName: llamastack-safety-demo-tls
      - configMap:
          name: pipeline-runtime-images
          optional: true
        name: runtime-images
