apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastack-trustyai-fms
  namespace: summit-connect-2025
spec:
  replicas: 1
  server:
    containerSpec:
      env:
        - name: VLLM_URL
          # Default to tinyllama-1b (faster deployment, requires 1 GPU)
          # Alternative: llama32-1b (better quality, requires 1 GPU)
          # Uses internal service name (same namespace) on port 8080
          # For llama32-1b: http://llama32-1b-predictor:8080/v1
          value: 'http://tinyllama-1b-predictor:8080/v1'
        - name: INFERENCE_MODEL
          value: 'tinyllama-1b'
        - name: MILVUS_DB_PATH
          value: '~/.llama/milvus.db'
        - name: VLLM_TLS_VERIFY
          value: 'false'
        - name: FMS_ORCHESTRATOR_URL
          value: 'http://guardrails-orchestrator-service:8033'
      name: llama-stack
      port: 8321
    distribution:
      name: rh-dev
    storage:
      size: 20Gi