apiVersion: v2
name: llamastack-playground
description: A Helm chart to deploy the LlamaStack Playground (Streamlit UI) on OpenShift
home: https://github.com/redhat-et/summit-connect-2025
icon: https://quay.io/repository/rh-aiservices-bu/llama-stack-playground?tab=info
keywords:
  - llamastack
  - streamlit
  - openshift
  - route
  - playground
  - vllm
  - kserve
sources:
  - https://quay.io/repository/rh-aiservices-bu/llama-stack-playground
  - https://github.com/llama-stack/llama-stack
maintainers:
  - name: Summit Connect 2025 Team
    email: noreply@example.com

# Helm 3 chart
version: 0.1.0
# App version tracks upstream image tag by default
appVersion: "0.2.11"
type: application
