# Default values for the LlamaStack Playground chart.
# These defaults mirror the original kustomize manifests under llamastack-playground/.

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: quay.io/rh-aiservices-bu/llama-stack-playground
  # By default, use the chart's appVersion. You can override with an explicit tag.
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

# Common labels to add to all resources (merged with Helm's standard labels)
commonLabels: {}

securityContext:
  # Pod-level security context
  pod: {
    runAsNonRoot: true
  }
  # Container-level security context
  container: {
    allowPrivilegeEscalation: false,
    readOnlyRootFilesystem: false,
    runAsNonRoot: true,
    capabilities: { drop: ["ALL"] }
  }

service:
  type: ClusterIP
  port: 80
  targetPortName: http

route:
  enabled: true
  host: "" # optional: if empty, router will generate
  tls:
    enabled: true
    termination: edge # edge | passthrough | reencrypt
    insecureEdgeTerminationPolicy: Redirect # Allow | None | Redirect
  annotations: {}
  labels: {}

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

container:
  name: llama-stack-playground
  portName: http
  port: 8501
  env:
    STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
    STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
    STREAMLIT_SERVER_PORT: "8501"
    LLAMA_STACK_ENDPOINT: "http://llamastack-service:8321"
    DEFAULT_MODEL: "llama32-3b"
  envExtra: [] # list of { name: ..., value: ... } or { name: ..., valueFrom: ... }

nodeSelector: {}

tolerations: []

affinity: {}

# Optional labels/annotations for resources
labels:
  deployment: {}
  service: {}
  route: {}
annotations:
  deployment: {}
  service: {}
  route: {}
