apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Default deployment configuration
# This references the single-gpu overlay for convenience
#
# Available overlays:
#   - overlays/single-gpu/  - Default, deploys tinyllama-1b only (1 GPU required)
#   - overlays/dual-gpu/    - Deploys both llama32-1b and tinyllama-1b (2 GPUs required)
#
# Usage:
#   Default (single GPU): oc apply -k demo/
#   Dual GPU:            oc apply -k demo/overlays/dual-gpu/

resources:
  - overlays/single-gpu