apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Default deployment configuration
# This references the single-gpu environment for convenience
#
# Available environments:
#   - environments/single-gpu/  - Default, deploys tinyllama-1b + granite-guardian (1 GPU required)
#   - environments/dual-gpu/    - Deploys llama-3-2-1b + tinyllama-1b + granite-guardian (2 GPUs required)
#
# Usage:
#   Default (single GPU): oc apply -k demo/
#   Dual GPU:            oc apply -k demo/environments/dual-gpu/
#   Individual component: oc apply -k demo/components/inference/tinyllama-1b/

resources:
  - environments/single-gpu