apiVersion: v1
data:
  URI: b2NpOi8vcXVheS5pby9yZWRoYXQtYWktc2VydmljZXMvbW9kZWxjYXItY2F0YWxvZzpncmFuaXRlLWd1YXJkaWFuLTMuMy04Yg==
kind: Secret
metadata:
  annotations:
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/description: ""
    openshift.io/display-name: granite-guardian-3-8b
  labels:
    opendatahub.io/dashboard: "true"
  name: granite-guardian-3-8b
  namespace: summit-connect-2025
type: Opaque
